#!/bin/bash

clear;
ant clean;

arg=("test" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine");

if [ -z $1 ]; then
    ant all && cat data/output;
else
    ant ${arg[$1]} && cat data/output;

    if [ -n $2 ]; then
        if [ "$2" = "dot" ]; then
            dot -Tpng dot.dot -o dot.png;
            dot -Tpng intermediate.dot -o intermediate.png;
            eog dot.png&
            eog intermediate.png&

            read -p 'Waiting input for closing...' yolo

            rm *.dot;
            rm *.png;
        fi
    fi
fi