#!/bin/bash

clear;
ant clean;

arg=("test" "one" "two" "three" "four" "five" "six" "seven" "height" "nine");

if [ -z $1 ]; then
    ant all && cat data/output;
else
    ant ${arg[$1]} && cat data/output;

    if [ -n $2 ]; then
        if [ "$2" = "dot" ]; then
            dot -Tpng dot.dot -o dot.png;
            eog dot.png;
        fi
    fi
fi